/* USER ACTIONS */

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGOUT = 'LOGOUT';

export const SEND_CODE_REQUEST = 'SEND_CODE_REQUEST';
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';
export const SEND_CODE_ERROR = 'SEND_CODE_ERROR';

export const CHECK_CODE_REQUEST = 'CHECK_CODE_REQUEST';
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const CHECK_CODE_ERROR = 'CHECK_CODE_ERROR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

/*  PARTY ACTIONS */
export const LOAD_PARTY_LIST_REQUEST = 'LOAD_PARTY_LIST_REQUEST';
export const LOAD_PARTY_LIST_SUCCESS = 'LOAD_PARTY_LIST_SUCCESS';
export const LOAD_PARTY_LIST_ERROR = 'LOAD_PARTY_LIST_ERROR';

export const CREATE_PARTY_REQUEST = 'CREATE_PARTY_REQUEST';
export const CREATE_PARTY_SUCCESS = 'CREATE_PARTY_SUCCESS';
export const CREATE_PARTY_ERROR = 'CREATE_PARTY_ERROR';

export const JOIN_PARTY_REQUEST = 'JOIN_PARTY_REQUEST';
export const JOIN_PARTY_SUCCESS = 'JOIN_PARTY_SUCCESS';
export const JOIN_PARTY_ERROR = 'JOIN_PARTY_ERROR';

export const CLOSE_PARTY_REQUEST = 'CLOSE_PARTY_REQUEST';
export const CLOSE_PARTY_SUCCESS = 'CLOSE_PARTY_SUCCESS';
export const CLOSE_PARTY_ERROR = 'CLOSE_PARTY_ERROR';